main: dev.alcor.rocketstrong.kitpvp.App
name: kitpvp
version: 1.0
api-version: 1.17
depend: [NBTAPI, ProtocolLib, ModelEngine]
commands:
   givegun:
      description: Obtain The Unholy Weapon
      usage: /<command> [GUN]
      permission: kitpvp.givegun
   kitpvp:
      description: Kitpvp Commands
      aliases:
         - kp
         - kpvp
      usage: /<command>
      permission: kitpvp.kitpvp